/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MisProyectosIndexRouteImport } from './routes/mis-proyectos/index'
import { Route as NudosIndexRouteImport } from './routes/nudos/index'
import { Route as NudosSlugRouteImport } from './routes/nudos/$slug'
import { Route as PatronesIndexRouteImport } from './routes/patrones/index'
import { Route as PatronesSlugRouteImport } from './routes/patrones/$slug'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MisProyectosIndexRoute = MisProyectosIndexRouteImport.update({
  id: '/mis-proyectos/',
  path: '/mis-proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NudosIndexRoute = NudosIndexRouteImport.update({
  id: '/nudos/',
  path: '/nudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NudosSlugRoute = NudosSlugRouteImport.update({
  id: '/nudos/$slug',
  path: '/nudos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronesIndexRoute = PatronesIndexRouteImport.update({
  id: '/patrones/',
  path: '/patrones/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronesSlugRoute = PatronesSlugRouteImport.update({
  id: '/patrones/$slug',
  path: '/patrones/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nudos/$slug': typeof NudosSlugRoute
  '/patrones/$slug': typeof PatronesSlugRoute
  '/mis-proyectos/': typeof MisProyectosIndexRoute
  '/nudos/': typeof NudosIndexRoute
  '/patrones/': typeof PatronesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nudos/$slug': typeof NudosSlugRoute
  '/patrones/$slug': typeof PatronesSlugRoute
  '/mis-proyectos': typeof MisProyectosIndexRoute
  '/nudos': typeof NudosIndexRoute
  '/patrones': typeof PatronesIndexRoute
  '/perfil': typeof PerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nudos/$slug': typeof NudosSlugRoute
  '/patrones/$slug': typeof PatronesSlugRoute
  '/mis-proyectos/': typeof MisProyectosIndexRoute
  '/nudos/': typeof NudosIndexRoute
  '/patrones/': typeof PatronesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nudos/$slug'
    | '/patrones/$slug'
    | '/mis-proyectos/'
    | '/nudos/'
    | '/patrones/'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nudos/$slug'
    | '/patrones/$slug'
    | '/mis-proyectos'
    | '/nudos'
    | '/patrones'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/nudos/$slug'
    | '/patrones/$slug'
    | '/mis-proyectos/'
    | '/nudos/'
    | '/patrones/'
    | '/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NudosSlugRoute: typeof NudosSlugRoute
  PatronesSlugRoute: typeof PatronesSlugRoute
  MisProyectosIndexRoute: typeof MisProyectosIndexRoute
  NudosIndexRoute: typeof NudosIndexRoute
  PatronesIndexRoute: typeof PatronesIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-proyectos/': {
      id: '/mis-proyectos/'
      path: '/mis-proyectos'
      fullPath: '/mis-proyectos/'
      preLoaderRoute: typeof MisProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nudos/': {
      id: '/nudos/'
      path: '/nudos'
      fullPath: '/nudos/'
      preLoaderRoute: typeof NudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nudos/$slug': {
      id: '/nudos/$slug'
      path: '/nudos/$slug'
      fullPath: '/nudos/$slug'
      preLoaderRoute: typeof NudosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrones/': {
      id: '/patrones/'
      path: '/patrones'
      fullPath: '/patrones/'
      preLoaderRoute: typeof PatronesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrones/$slug': {
      id: '/patrones/$slug'
      path: '/patrones/$slug'
      fullPath: '/patrones/$slug'
      preLoaderRoute: typeof PatronesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NudosSlugRoute: NudosSlugRoute,
  PatronesSlugRoute: PatronesSlugRoute,
  MisProyectosIndexRoute: MisProyectosIndexRoute,
  NudosIndexRoute: NudosIndexRoute,
  PatronesIndexRoute: PatronesIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
